configure_dotfiles: true
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - Keynote
  - Numbers
  - Pages
  - "App Store"

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 0
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 1
  - name: "Calibre"
    path: "/Applications/calibre.app/"
    pos: 2

dotfiles_repo: https://github.com/ryanzhou7/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore

homebrew_installed_packages:
  - mise
  - yarn
  - bash

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - visual-studio-code
  - calibre

# Set to 'true' to configure Sublime Text.
configure_sublime: false
